import {
  DEFAULT_GENERATION_OPTIONS,
  MODEL_REGISTRY_IDS,
} from "../constants/ai";
import type {
  AIProvider,
  AIModel,
  ChatRequest,
  ChatResponse,
  GenerationOptions,
  ProviderType,
} from "../types/ai";

function generateId(): string {
  return `mock-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}

function buildResponse(
  request: ChatRequest,
  content: string,
  _options: GenerationOptions,
): ChatResponse {
  const promptTokens = request.messages.reduce(
    (acc, m) => acc + m.content.split(/\s+/).length,
    0,
  );
  const completionTokens = content.split(/\s+/).length;

  return {
    id: generateId(),
    model: request.model,
    provider: "mock" as ProviderType,
    message: {
      role: "assistant",
      content,
    },
    usage: {
      promptTokens,
      completionTokens,
      totalTokens: promptTokens + completionTokens,
    },
    finishReason: "stop",
  };
}

function generateChatResponse(
  request: ChatRequest,
  options: GenerationOptions,
): ChatResponse {
  const userMessage = request.messages.find((m) => m.role === "user");
  const systemMessage = request.messages.find((m) => m.role === "system");
  const prompt = userMessage?.content ?? "";
  const prefix = systemMessage
    ? `[Context: ${systemMessage.content.slice(0, 40)}...]\n`
    : "";

  const responses: Record<string, string> = {
    hello: "Hello from Aether AI Mock Provider. How can I assist you today?",
    "what is aether":
      "Aether AI is an enterprise AI workspace platform designed for team collaboration, prompt management, and multi-agent workflows.",
    "what can you do":
      "I can assist with chat conversations, text completion, content generation, and various AI-powered tasks within the Aether AI platform.",
  };

  const lower = prompt.toLowerCase().trim();
  const matchKey = Object.keys(responses).find((k) => lower.startsWith(k));
  const content = matchKey
    ? responses[matchKey]
    : `${prefix}You said: "${prompt.slice(0, 100)}"\n\nThis is a deterministic response from the Aether AI Mock Provider. Configure a real provider (OpenAI, Anthropic, etc.) to receive AI-generated responses.`;

  return buildResponse(request, content, options);
}

function generateCompletionResponse(
  request: ChatRequest,
  options: GenerationOptions,
): ChatResponse {
  const userMessage = request.messages.find((m) => m.role === "user");
  const prompt = userMessage?.content ?? "";

  const content = `[Completion Result]\nInput: ${prompt.slice(0, 80)}\n---\nCompleted by Aether AI Mock Provider (completion mode).`;

  return buildResponse(request, content, options);
}

function generateEmbeddingResponse(
  request: ChatRequest,
  options: GenerationOptions,
): ChatResponse {
  const userMessage = request.messages.find((m) => m.role === "user");
  const prompt = userMessage?.content ?? "";

  const content = `[Embedding Vector]\nInput: "${prompt.slice(0, 60)}"\nDimensions: 1536\n---\nGenerated by Aether AI Mock Provider (embedding mode). Embedding vector data omitted.`;

  return buildResponse(request, content, options);
}

const MODELS: AIModel[] = [
  {
    id: MODEL_REGISTRY_IDS.MOCK_CHAT,
    provider: "mock",
    name: "Mock Chat",
    capabilities: ["chat", "streaming"],
    description: "Mock provider for chat-based AI interactions.",
    maxTokens: 4096,
    supportsStreaming: true,
  },
  {
    id: MODEL_REGISTRY_IDS.MOCK_COMPLETION,
    provider: "mock",
    name: "Mock Completion",
    capabilities: ["completion"],
    description: "Mock provider for text completion tasks.",
    maxTokens: 4096,
    supportsStreaming: false,
  },
  {
    id: MODEL_REGISTRY_IDS.MOCK_EMBEDDING,
    provider: "mock",
    name: "Mock Embedding",
    capabilities: ["embedding"],
    description: "Mock provider for embedding generation.",
    maxTokens: 8192,
    supportsStreaming: false,
  },
];

export class MockProvider implements AIProvider {
  readonly type = "mock" as ProviderType;
  readonly name = "Mock Provider";

  async generate(
    request: ChatRequest,
    options?: GenerationOptions,
  ): Promise<ChatResponse> {
    const resolvedOptions = { ...DEFAULT_GENERATION_OPTIONS, ...options };
    const model = MODELS.find((m) => m.id === request.model);

    if (!model) {
      return {
        id: generateId(),
        model: request.model,
        provider: "mock",
        message: {
          role: "assistant",
          content: `Unknown model: ${request.model}. Available mock models: ${MODELS.map((m) => m.id).join(", ")}.`,
        },
        usage: { promptTokens: 0, completionTokens: 0, totalTokens: 0 },
        finishReason: "error",
      };
    }

    if (model.capabilities.includes("completion") && !model.capabilities.includes("chat")) {
      return generateCompletionResponse(request, resolvedOptions);
    }

    if (model.capabilities.includes("embedding")) {
      return generateEmbeddingResponse(request, resolvedOptions);
    }

    return generateChatResponse(request, resolvedOptions);
  }

  async *stream(
    request: ChatRequest,
    options?: GenerationOptions,
  ): AsyncIterable<ChatResponse> {
    const resolvedOptions = { ...DEFAULT_GENERATION_OPTIONS, ...options };
    const full = await this.generate(request, resolvedOptions);
    const words = full.message.content.split(" ");
    for (let i = 0; i < words.length; i++) {
      yield {
        ...full,
        id: `${full.id}-chunk-${i}`,
        message: { role: "assistant", content: words[i] + (i < words.length - 1 ? " " : "") },
      };
    }
  }

  async listModels(): Promise<AIModel[]> {
    return MODELS;
  }

  async healthCheck(): Promise<boolean> {
    return true;
  }
}
